apiVersion: v1
kind: Namespace
metadata:
  name: rhacm-policies
  labels:
    app.kubernetes.io/name: rhacm-policies
    app.kubernetes.io/part-of: crowdstrike-falcon
    openshift.io/cluster-monitoring: "true"
