apiVersion: cluster.open-cluster-management.io/v1beta1
kind: Placement
metadata:
  labels:
    app.kubernetes.io/managed-by: policy-generator
    app.kubernetes.io/name: falcon-operator
    app.kubernetes.io/part-of: crowdstrike-falcon
  name: placement-falcon-operator
  namespace: rhacm-policies
spec:
  predicates:
  - requiredClusterSelector:
      labelSelector:
        matchExpressions:
        - key: vendor
          operator: In
          values:
          - OpenShift
  tolerations:
  - effect: NoSchedule
    key: cluster.open-cluster-management.io/unreachable
    operator: Exists
  - effect: NoSchedule
    key: cluster.open-cluster-management.io/unavailable
    operator: Exists
---
apiVersion: policy.open-cluster-management.io/v1
kind: PlacementBinding
metadata:
  labels:
    app.kubernetes.io/managed-by: policy-generator
    app.kubernetes.io/part-of: crowdstrike-falcon
  name: binding-policy-falcon-operator-install
  namespace: rhacm-policies
placementRef:
  apiGroup: cluster.open-cluster-management.io
  kind: Placement
  name: placement-falcon-operator
subjects:
- apiGroup: policy.open-cluster-management.io
  kind: Policy
  name: policy-falcon-operator-install
---
apiVersion: policy.open-cluster-management.io/v1
kind: Policy
metadata:
  annotations:
    policy.open-cluster-management.io/categories: CM Configuration Management
    policy.open-cluster-management.io/controls: CM-2 Baseline Configuration
    policy.open-cluster-management.io/description: ""
    policy.open-cluster-management.io/standards: NIST SP 800-53
  labels:
    app.kubernetes.io/managed-by: policy-generator
    app.kubernetes.io/part-of: crowdstrike-falcon
  name: policy-falcon-operator-install
  namespace: rhacm-policies
spec:
  disabled: false
  policy-templates:
  - objectDefinition:
      apiVersion: policy.open-cluster-management.io/v1
      kind: ConfigurationPolicy
      metadata:
        name: policy-falcon-operator-install
      spec:
        object-templates:
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Namespace
            metadata:
              labels:
                app.kubernetes.io/managed-by: acm-policy
                app.kubernetes.io/name: falcon-operator
                app.kubernetes.io/part-of: crowdstrike-falcon
                openshift.io/cluster-monitoring: "true"
                pod-security.kubernetes.io/audit: privileged
                pod-security.kubernetes.io/enforce: privileged
                pod-security.kubernetes.io/warn: privileged
              name: falcon-operator
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Namespace
            metadata:
              labels:
                app.kubernetes.io/managed-by: acm-policy
                app.kubernetes.io/name: falcon-system
                app.kubernetes.io/part-of: crowdstrike-falcon
                openshift.io/cluster-monitoring: "true"
                pod-security.kubernetes.io/audit: privileged
                pod-security.kubernetes.io/enforce: privileged
                pod-security.kubernetes.io/warn: privileged
              name: falcon-system
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Namespace
            metadata:
              labels:
                app.kubernetes.io/managed-by: acm-policy
                app.kubernetes.io/name: falcon-kac
                app.kubernetes.io/part-of: crowdstrike-falcon
                openshift.io/cluster-monitoring: "true"
                pod-security.kubernetes.io/audit: privileged
                pod-security.kubernetes.io/enforce: privileged
                pod-security.kubernetes.io/warn: privileged
              name: falcon-kac
        - complianceType: musthave
          objectDefinition:
            apiVersion: v1
            kind: Namespace
            metadata:
              labels:
                app.kubernetes.io/managed-by: acm-policy
                app.kubernetes.io/name: falcon-image-analyzer
                app.kubernetes.io/part-of: crowdstrike-falcon
                openshift.io/cluster-monitoring: "true"
                pod-security.kubernetes.io/audit: privileged
                pod-security.kubernetes.io/enforce: privileged
                pod-security.kubernetes.io/warn: privileged
              name: falcon-image-analyzer
        - complianceType: musthave
          objectDefinition:
            apiVersion: operators.coreos.com/v1
            kind: OperatorGroup
            metadata:
              labels:
                app.kubernetes.io/managed-by: acm-policy
                app.kubernetes.io/name: falcon-operator
                app.kubernetes.io/part-of: crowdstrike-falcon
              name: falcon-operator
              namespace: falcon-operator
            spec:
              upgradeStrategy: Default
        - complianceType: musthave
          objectDefinition:
            apiVersion: operators.coreos.com/v1alpha1
            kind: Subscription
            metadata:
              labels:
                app.kubernetes.io/managed-by: acm-policy
                app.kubernetes.io/name: falcon-operator
                app.kubernetes.io/part-of: crowdstrike-falcon
              name: falcon-operator
              namespace: falcon-operator
            spec:
              channel: certified-1.0
              config:
                env:
                - name: ARGS
                  value: --leader-elect --lease-duration=60s --renew-deadline=45s
              installPlanApproval: Manual
              name: falcon-operator
              source: certified-operators
              sourceNamespace: openshift-marketplace
              startingCSV: falcon-operator.v1.15.0
        pruneObjectBehavior: DeleteIfCreated
        remediationAction: enforce
        severity: high
  remediationAction: enforce
